.TH "Courier" "1" "07 November 2023" "Courier VERSION" ""
.hy

.SH NAME
.PP
courier

.SH SYNOPSIS
.PP
\f[B]courier\f[R] [options] [file]

.SH DESCRIPTION
.PP
Customizable pager inspired in software-design by suckless software and written
for hui.
Customizations are done in cfg/config.h before compilation.
The cfg_example directory shows elaborate examples, which are also used in the
debug builds.
The debug builds are created by calling 'make d_' and then the program name.
This way you can quickly get a feeling for what is possible with the config.

.SH OPTIONS

.TP
.B \-v
prints version information then exits

.TP
.B \-a
prints program name, version, license and repository information then exits

.TP
.B \-t
takes an argument and prints given string as title below the header

.SH USAGE PER DEFAULT

.B q, h
quit the program

.B j
go down

.B k
go up

.B :
enter the internal command line

.SH COMMAND LINE COMMANDS

.B q quit exit
quit the program

.B NUMBER
when given a positive number, it is used as a line number to scroll to

.SH SEE ALSO
hui(1)

.SH COPYRIGHT
.PP
House User Interface Copyright (C) 2022 - 2023 Andy Frank Schoknecht
.PP
This program is licensed under the BSD-3-Clause license.
You should have received a copy of the license along with this program.

The source code of this program is available at:
https://github.com/SchokiCoder/hui

.SH AUTHOR
Andy Frank Schoknecht
