.TH "HUI" "1" "15 April 2023" "hui VERSION" ""
.hy

.SH NAME
.PP
hui \- House User Interface

.SH SYNOPSIS
.PP
\f[B]hui\f[R] [options]

.SH DESCRIPTION
.PP
Customizable terminal based user-interface for common tasks and personal tastes,
inspired by suckless software.
The user can create and customize menus with submenus and commands in the
config header file.
In the source code directory "cfg_example" there are elaborate examples for both
the "config.h" and "scripts.h".
These files are also used in the debug build.
So by running 'make debug' and starting './hui' you can quickly get a feeling
for what is possible with the config and scripting system.

.SH OPTIONS

.TP
.B \-v
prints version information then exits

.TP
.B \-a
prints program name, version, license and repository information then exits

.SH DEFAULT USAGE

.B q
quit the program

.B :
enter the command line

.B h
go back

.B j
go down

.B k
go up

.B l
go into submenu

.B L
execute command

.SH COMMAND LINE COMMANDS

.B q quit exit
quit the program

.SH COPYRIGHT
.PP
House User Interface Copyright (C) 2022 - 2023 Andy Frank Schoknecht
.PP
This program is licensed under the BSD-3-Clause license.
You should have received a copy of the license along with this program.

The source code of this program is available at:
https://github.com/SchokiCoder/hui

.SH AUTHOR
Andy Frank Schoknecht
